name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ImageMagick
        run: choco install imagemagick -y

      - name: Add ImageMagick to PATH
        run: |
          $path = Get-ChildItem "C:\Program Files" -Filter "ImageMagick-*" | Select-Object -First 1
          echo "$($path.FullName)" >> $env:GITHUB_PATH

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\install

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CelestiaContent
          path: install
